### ISSUE TITLE
dmesg floods "copygc requested to run but found no buckets to move!" [de2fbf8]

### ISSUE THREAD

**Issue by jpsollie** [koverstreet/bcachefs#407]
de2fbf8b875fd8e61cc9a583d073f5527e3cb8e7 patched to 5.16.16

**Generic info**
Provide the output of:
bcachefs fs usage
```
Filesystem: bb48bd29-a3a2-46fe-b7d5-243c70dfef63
Size:                  2004982589440
Used:                   119367948288
Online reserved:                   0

Data type       Required/total  Devices
btree:          1/2             [sde1 sdm1]                  1048576
btree:          1/2             [sdd1 sdc5]                209715200
btree:          1/2             [sde1 sdc5]                 80216064
btree:          1/2             [sdd1 sdl1]                 87556096
btree:          1/2             [sde1 sdl1]                227540992
btree:          1/2             [sdc5 sdl1]                  7340032
btree:          1/2             [sdd1 sde1]                  8912896
user:           1/1             [sdg]                   113020393472
cached:         1/1             [nvme0n1p5]              46115096064
cached:         1/1             [sdm1]                   25105395200

HDD (device 0):                  sdg              rw
                                data         buckets      fragmented
  free:                            0         3589587
  sb:                        3149824               7          520192
  journal:                4294967296            8192
  btree:                           0               0
  user:                 113020393472          215570          370688
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:            1999296790528         3813356

SSDC (device 5):           nvme0n1p5              rw
                                data         buckets      fragmented
  free:                            0           19914
  sb:                        3149824              13          258048
  journal:                 406061056            1549
  btree:                           0               0
  user:                            0               0
  cached:                46115096064          176888
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:              51999932416          198364

SSDC (device 6):                sdm1              rw
                                data         buckets      fragmented
  free:                            0             803
  sb:                        3149824              13          258048
  journal:                 200015872             763
  btree:                      524288               2
  user:                            0               0
  cached:                25105395200           96099
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:              25606225920           97680

SSDM (device 3):                sdc5              rw
                                data         buckets      fragmented
  free:                            0           96341
  sb:                        3149824              13          258048
  journal:                 200015872             763
  btree:                   148635648             567
  user:                            0               0
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:              25607274496           97684

SSDM (device 1):                sdd1              rw
                                data         buckets      fragmented
  free:                            0           96320
  sb:                        3149824              13          258048
  journal:                 200015872             763
  btree:                   153092096             584
  user:                            0               0
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:              25606225920           97680

SSDM (device 2):                sde1              rw
                                data         buckets      fragmented
  free:                            0           96298
  sb:                        3149824              13          258048
  journal:                 200015872             763
  btree:                   158859264             606
  user:                            0               0
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:              25606225920           97680

SSDM (device 4):                sdl1              rw
                                data         buckets      fragmented
  free:                            0           96289
  sb:                        3149824              13          258048
  journal:                 200015872             763
  btree:                   161218560             615
  user:                            0               0
  cached:                          0               0
  parity:                          0               0
  stripe:                          0               0
  need_gc_gens:                    0               0
  need_discard:                    0               0
  erasure coded:                   0               0
  capacity:              25606225920           97680
```
bcachefs show-super
```
External UUID:                  bb48bd29-a3a2-46fe-b7d5-243c70dfef63
Internal UUID:                  f21b7785-3e2b-454c-85b3-535f52020d77
Device index:                   0
Label:                          distfiles
Version:                        new_data_types
Oldest version on disk:         inode_v2
Created:                        Mon May 31 09:48:40 2021
Sequence number:                470
Superblock size:                71960
Clean:                          0
Devices:                        7
Sections:                       journal,members,replicas_v0,disk_groups,clean,journal_seq_blacklist
Features:                       journal_seq_blacklist_v3,reflink,new_siphash,inline_data,new_extent_overwrite,btree_ptr_v2,extents_above_btree_updates,btree_updates_journalled,new_varint,journal_no_flush,alloc_v2,extents_across_btree_nodes
Compat features:                alloc_info,alloc_metadata,extents_above_btree_updates_done,bformat_overflow_done

Options:
  block_size:                   512
  btree_node_size:              256k
  errors:                       continue [ro] panic 
  metadata_replicas:            2
  data_replicas:                1
  metadata_replicas_required:   1
  data_replicas_required:       1
  encoded_extent_max:           64k
  metadata_checksum:            none [crc32c] crc64 xxhash 
  data_checksum:                none [crc32c] crc64 xxhash 
  compression:                  [none] lz4 gzip zstd 
  background_compression:       [none] lz4 gzip zstd 
  str_hash:                     crc32c crc64 [siphash] 
  metadata_target:              SSDM
  foreground_target:            SSDC
  background_target:            HDD
  promote_target:               SSDC
  erasure_code:                 0
  inodes_32bit:                 0
  shard_inode_numbers:          0
  inodes_use_key_cache:         0
  gc_reserve_percent:           8
  gc_reserve_bytes:             0
  root_reserve_percent:         0
  wide_macs:                    0
  acl:                          1
  usrquota:                     0
  grpquota:                     0
  prjquota:                     0
  journal_flush_delay:          1000
  journal_flush_disabled:       0
  journal_reclaim_delay:        1000
  journal_transaction_names:    0

members (size 400):
  Device:                       0
    UUID:                       74dfa271-da3f-4755-b6d7-35e3a20fe1b7
    Size:                       1.8T
    Bucket size:                512k
    First bucket:               0
    Buckets:                    3813356
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      HDD (0)
    Data allowed:               journal,btree,user
    Has data:                   user
    Discard:                    0
    Freespace initialized:      1
  Device:                       1
    UUID:                       f03dd045-242d-4f44-abe7-1889266f1018
    Size:                       23.8G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    97680
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      SSDM (1)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree
    Discard:                    1
    Freespace initialized:      1
  Device:                       2
    UUID:                       b464f770-bc56-4563-990e-f6614cd71f56
    Size:                       23.8G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    97680
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      SSDM (1)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree
    Discard:                    1
    Freespace initialized:      1
  Device:                       3
    UUID:                       310ddf84-5bc5-4c48-8187-1472639161a2
    Size:                       23.8G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    97684
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      SSDM (1)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree
    Discard:                    1
    Freespace initialized:      1
  Device:                       4
    UUID:                       256a9a9e-c344-4697-92c2-7ed7181e76a2
    Size:                       23.8G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    97680
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      SSDM (1)
    Data allowed:               journal,btree,user
    Has data:                   journal,btree
    Discard:                    1
    Freespace initialized:      1
  Device:                       5
    UUID:                       fe4513c5-1015-47a8-9262-4517182786fc
    Size:                       48.4G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    198364
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      SSDC (2)
    Data allowed:               journal,btree,user
    Has data:                   user,cached
    Discard:                    1
    Freespace initialized:      1
  Device:                       6
    UUID:                       2ef854d7-6aec-4ad2-98bf-7a0d65d9d850
    Size:                       23.8G
    Bucket size:                256k
    First bucket:               0
    Buckets:                    97680
    Last mount:                 Tue Apr 12 12:40:31 2022
    State:                      rw
    Group:                      SSDC (2)
    Data allowed:               journal,btree,user
    Has data:                   btree,user,cached
    Discard:                    1
    Freespace initialized:      1
```
when mounting this fs, copygc floods the dmesg with error messages similar to these, even after mount finishes:
```
bcachefs (bb48bd29-a3a2-46fe-b7d5-243c70dfef63): copygc requested to run but found no buckets to move!
```
the CPU usage of copygc jumps to 100%
```
root      8153  100  0.0      0     0 ?        R    12:40   6:58 [bch-copygc/bb48]
```
the fs is perfectly readable though.
I tried bcachefs fsck -f -y, but it did not fix anything

This is not the case for another fs installed on the same PC, so I attached the list_journal, maybe it tells something useful, as "request to run some copy operation" looks like an unfinished transaction to me:
```
recovering from clean shutdown, journal seq 276796
ja->sectors_free == ca->mi.bucket_size
cur_idx 226/763
bucket_seq[225] = 276678
bucket_seq[226] = 276784
bucket_seq[227] = 226217
journal read done, 0 keys in 1 entries, seq 276797
mounted version=new_data_types opts=errors=continue,metadata_replicas=2,metadata_target=SSDM,foreground_target=SSDC,background_target=HDD,promote_target=SSDC,noinodes_32bit,noshard_inode_numbers,noinodes_use_key_cache,degraded,journal_reclaim_delay=1000,fix_errors,nochanges,norecovery,nojournal_transaction_names
journal entry       276796
  version         21
  last seq        276796
  flush           1
  written at      2:210:91 (sector 287323) 3:261:91 (sector 261211)
    btree_keys: 
    btree_root: btree=extents l=1 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq 6efc8e8b2d41ec2a written 329 min_key POS_MIN ptr: 3:852:0 gen 0 ptr: 1:850:0 gen 0
    btree_root: btree=inodes l=1 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq c4ad314f8e99652d written 135 min_key POS_MIN ptr: 3:870:0 gen 0 ptr: 1:869:0 gen 0
    btree_root: btree=dirents l=1 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq e324b77841adbc1c written 272 min_key POS_MIN ptr: 3:55775:0 gen 3 ptr: 1:56484:0 gen 3
    btree_root: btree=xattrs l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq d9238e9b1a9d001 written 42 min_key POS_MIN ptr: 4:43256:0 gen 1 ptr: 2:44022:0 gen 1
    btree_root: btree=alloc l=1 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq e76257571e62ee1 written 70 min_key POS_MIN ptr: 3:868:0 gen 1 ptr: 1:871:0 gen 1
    btree_root: btree=quotas l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq e8214f43dd3ea6dc written 1 min_key POS_MIN ptr: 3:43782:0 gen 1 ptr: 1:44500:0 gen 1
    btree_root: btree=stripes l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq dc9e644fcf35c786 written 1 min_key POS_MIN ptr: 2:44163:0 gen 1 ptr: 4:43397:0 gen 1
    btree_root: btree=reflink l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq e1d02f25ad1fb58a written 6 min_key POS_MIN ptr: 3:43783:0 gen 1 ptr: 1:44501:0 gen 1
    btree_root: btree=subvolumes l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq e5da6a5fff86e written 1 min_key POS_MIN ptr: 2:44166:0 gen 1 ptr: 4:43400:0 gen 1
    btree_root: btree=snapshots l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq 3ed761ebb3cb3995 written 1 min_key POS_MIN ptr: 3:43786:0 gen 1 ptr: 1:44504:0 gen 1
    btree_root: btree=lru l=1 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq a15f0b448b5f35d0 written 486 min_key POS_MIN ptr: 2:781:0 gen 0 ptr: 4:782:0 gen 0
    btree_root: btree=freespace l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq 871793ecdf727276 written 351 min_key POS_MIN ptr: 2:779:0 gen 1 ptr: 4:780:0 gen 1
    btree_root: btree=need_discard l=0 u64s 12 type btree_ptr_v2 SPOS_MAX len 0 ver 0: seq 181a45ee66729e84 written 32 min_key POS_MIN ptr: 3:864:0 gen 1 ptr: 4:909:0 gen 1
    usage: type=inodes v=11952
    usage: type=key_version v=0
    usage: type=reserved v=0
    usage: type=reserved v=0
    usage: type=reserved v=0
    usage: type=reserved v=0
    data_usage: btree: 1/2 [2 6]=2048
    data_usage: btree: 1/2 [1 3]=409600
    data_usage: user: 1/1 [5]=0
    data_usage: journal: 1/2 [2 3]=0
    data_usage: btree: 1/2 [2 3]=156672
    data_usage: btree: 1/2 [3 6]=0
    data_usage: cached: 1/1 [5]=90068547
    data_usage: journal: 1/2 [1 3]=0
    data_usage: journal: 1/2 [3 4]=0
    data_usage: btree: 1/2 [1 4]=171008
    data_usage: btree: 1/2 [2 4]=444416
    data_usage: btree: 1/2 [3 4]=14336
    data_usage: user: 1/1 [0]=220742956
    data_usage: user: 1/1 [6]=0
    data_usage: cached: 1/1 [6]=49033975
    data_usage: journal: 1/2 [1 2]=0
    data_usage: journal: 1/2 [1 4]=0
    data_usage: journal: 1/2 [2 4]=0
    data_usage: btree: 1/2 [1 2]=17408
    dev_usage: dev=0 free: buckets=3589587 sectors=0 fragmented=0 sb: buckets=7 sectors=6152 fragmented=1016 journal: buckets=8192 sectors=8388608 fragmented=0 btree: buckets=0 sectors=0 fragmented=0 user: buckets=215570 sectors=220742956 fragmented=724 cached: buckets=0 sectors=0 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    dev_usage: dev=1 free: buckets=96320 sectors=0 fragmented=0 sb: buckets=13 sectors=6152 fragmented=504 journal: buckets=763 sectors=390656 fragmented=0 btree: buckets=584 sectors=299008 fragmented=0 user: buckets=0 sectors=0 fragmented=0 cached: buckets=0 sectors=0 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    dev_usage: dev=2 free: buckets=96298 sectors=0 fragmented=0 sb: buckets=13 sectors=6152 fragmented=504 journal: buckets=763 sectors=390656 fragmented=0 btree: buckets=606 sectors=310272 fragmented=0 user: buckets=0 sectors=0 fragmented=0 cached: buckets=0 sectors=0 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    dev_usage: dev=3 free: buckets=96341 sectors=0 fragmented=0 sb: buckets=13 sectors=6152 fragmented=504 journal: buckets=763 sectors=390656 fragmented=0 btree: buckets=567 sectors=290304 fragmented=0 user: buckets=0 sectors=0 fragmented=0 cached: buckets=0 sectors=0 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    dev_usage: dev=4 free: buckets=96289 sectors=0 fragmented=0 sb: buckets=13 sectors=6152 fragmented=504 journal: buckets=763 sectors=390656 fragmented=0 btree: buckets=615 sectors=314880 fragmented=0 user: buckets=0 sectors=0 fragmented=0 cached: buckets=0 sectors=0 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    dev_usage: dev=5 free: buckets=19914 sectors=0 fragmented=0 sb: buckets=13 sectors=6152 fragmented=504 journal: buckets=1549 sectors=793088 fragmented=0 btree: buckets=0 sectors=0 fragmented=0 user: buckets=0 sectors=0 fragmented=0 cached: buckets=176888 sectors=90068547 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    dev_usage: dev=6 free: buckets=803 sectors=0 fragmented=0 sb: buckets=13 sectors=6152 fragmented=504 journal: buckets=763 sectors=390656 fragmented=0 btree: buckets=2 sectors=1024 fragmented=0 user: buckets=0 sectors=0 fragmented=0 cached: buckets=96099 sectors=49033975 fragmented=0 parity: buckets=0 sectors=0 fragmented=0 stripe: buckets=0 sectors=0 fragmented=0 need_gc_gens: buckets=0 sectors=0 fragmented=0 need_discard: buckets=0 sectors=0 fragmented=0 buckets_ec: 0
    clock: read=1024928805
    clock: write=1658660527
```
